<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-TapHoa.Worker-b310ab3b-7e9e-4275-b958-29d724be5b45</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.2.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\TapHoa.Application\TapHoa.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\TapHoa.Infrastructure\TapHoa.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Infrastructure\TapHoa.Persistence\TapHoa.Persistence.csproj" />
    <ProjectReference Include="..\..\SharedKernel\TapHoa.Utilities\TapHoa.Utilities.csproj" />
  </ItemGroup>
</Project>
